name: Ruby RSpec Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CP_CLIENT_ID: ${{ secrets.CP_CLIENT_ID }}
      CP_LICENCE_KEY: ${{ secrets.CP_LICENCE_KEY }}
      CP_MERCHANT_ID: ${{ secrets.CP_MERCHANT_ID }}
    strategy:
      matrix:
        ruby-version: [2.7, 3.0, 3.3]

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ matrix.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-${{ matrix.ruby-version }}-
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec
      - run: gem build citypay_api_client.gemspec
      - run: gem install ./citypay_api_client-1.1.3.gem


  build-and-publish:
    runs-on: ubuntu-latest  # The type of runner that the job will run on
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Specify the Ruby version

      - name: Install dependencies
        run: gem install bundler && bundle install

      - name: Build gem
        run: gem build *.gemspec

      - name: Push gem to RubyGems.org
        run: gem push *.gem --key github
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_APIKEY }}