name: Ruby RSpec Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CP_CLIENT_ID: ${{ secrets.CP_CLIENT_ID }}
      CP_LICENCE_KEY: ${{ secrets.CP_LICENCE_KEY }}
      CP_MERCHANT_ID: ${{ secrets.CP_MERCHANT_ID }}
    strategy:
      matrix:
        ruby-version: [2.7, 2.9, 3.0, 3.3]

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ matrix.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-${{ matrix.ruby-version }}-
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec
      - run: gem build citypay_api_client.gemspec
      - run: gem install ./citypay_api_client-1.1.2.gem